this.reload() error help
Uncaught TypeError: this.reload is not a function

Trying to call reload method before its defined so this.forwardDriection and this.subAnnual will be defined for this.dialog().